### ISSUE TITLE
Try out manually building a docker-compose spec that runs a fondant pipeline

### ISSUE THREAD

**Issue by GeorgesLorre** [ml6team/fondant#184]

**Comment by GeorgesLorre** [comment]
I created a first version using the starcoder example which I was able to run succesfully

**features:
- bind mount: so everything (data + manifests) is stored to a local folder
- build: we build the images dynamically instead of referencing the already built ones
- depends_on: this makes sure that the components run in the right sequence
- logs: docker compose generates nice coloured logs so you can easily see the logs per component
- rerunning single steps: I think this should be possible but needs more looking into**

```
version: '3.8'
services:
  load_from_hub:
    build:
      context: ./components/load_from_hub_stack
      dockerfile: Dockerfile
    command: ["--metadata", '{"run_id":"test_georges", "base_path":"/artifacts"}', "--output_manifest_path", "/artifacts/manifest/manifest.txt", "--dataset_name", "ml6team/the-stack-smol-python"]
    volumes:
      - type: bind
        source: /Users/georgeslorre/ML6/internal/express/playground/artifacts
        target: /artifacts

  lang_filter:
    build:
      context: ./components/lang_filter
      dockerfile: Dockerfile
    command: ["--metadata", '{"run_id":"test_georges", "base_path":"/artifacts"}', "--input_manifest_path", "/artifacts/manifest/manifest.txt", "--output_manifest_path", "/artifacts/manifest/manifest.txt", "--lang", "Python"]
    depends_on:
      load_from_hub:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: /Users/georgeslorre/ML6/internal/express/playground/artifacts
        target: /artifacts
  
  pii_redaction:
    build:
      context: ./components/pii_redaction
      dockerfile: Dockerfile
    command: ["--metadata", '{"run_id":"test_georges", "base_path":"/artifacts"}', "--input_manifest_path", "/artifacts/manifest/manifest.txt", "--output_manifest_path", "/artifacts/manifest/manifest.txt"]
    depends_on:
      lang_filter:
        condition: service_completed_successfully

    volumes:
      - type: bind
        source: /Users/georgeslorre/ML6/internal/express/playground/artifacts
        target: /artifacts

volumes:
  artifacts:
```
