### ISSUE TITLE
Create a reusable file loader component

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant#290]
It would be useful to have a reusable file loader component which can load data from files in a directory.

It should translate the following directory structure:
```
|- data_directory
   |- filename_1
   |- filename_2
   |- filename_3
```

To the following Dask dataframe:

| id | file_content |
|--- | --- |
| filename_1 | file 1 content |
| filename_2 | file 2 content |
| filename_3 | file 3 content |

A minimal component specification would look like:
```yaml
name: Load from files
description: Component that loads a dataset from files
image: ghcr.io/ml6team/load_from_files:dev

produces:
  file:
    fields:
      content:
        type: binary

args:
  path:
    description: Local or remote path to the directory containing the files
    type: str
```

Some notes:
- We can make the component "generic" as a next step (meaning it can handle dynamic component specifications)
- Remote paths should work out of the box if the component installs `fondant[aws,azure,gcp]`.
- We can add additional functionality later (eg. handling subdirectories, taking additional arguments, ...
